mutation assignSiteBwLicense($accountId: ID!,$input: AssignSiteBwLicenseInput!) {
      sites(accountId: $accountId) {
            assignSiteBwLicense(input: $input) {
                license {
                    id
                    status
                    plan
                    sku
                    ... on PooledBandwidthLicense {
                        siteLicenseType
                        siteLicenseGroup
                        total
                        accounts {
                            allocatedBandwidth
                            account {
                                id
                                name
                            }
                        }
                        sites {
                            allocatedBandwidth
                            site {
                                id
                                name
                            }
                        }
                    }
                }
            }
        }
}