mutation popLocationMutationsReleaseIp ( $accountId:ID! $popLocationReleaseIpInput:PopLocationReleaseIpInput!) {
	popLocationMutations ( accountId:$accountId ) {
		releaseIp ( input:$popLocationReleaseIpInput  )  {
			allocatedIp {
				id
				account {
					id
					name
				}
				ip
				popLocation {
					id
					name
				}
				allocationType
				description
				subnet
				state
			}
		}
	}	
}