mutation ztnaAppConnectorAddZtnaAppConnectorsConfiguration ( $accountId:ID! $addZtnaAppConnectorsConfigurationInput:AddZtnaAppConnectorsConfigurationInput!) {
	ztnaAppConnector ( accountId:$accountId ) {
		addZtnaAppConnectorsConfiguration ( input:$addZtnaAppConnectorsConfigurationInput  )  {
			ztnaAppConnectorsConfiguration {
				privateAppsServiceRange
				appConnectorManagementRange
			}
		}
	}	
}