mutation businessPlatformUpdateSettings ( $accountId:ID! $businessPlatformUpdateSettingsInput:BusinessPlatformUpdateSettingsInput!) {
	businessPlatform ( accountId:$accountId ) {
		updateSettings ( input:$businessPlatformUpdateSettingsInput  )  {
			approvalEnabled
		}
	}	
}