mutation sitesRemoveSecondaryGcpVSocket ( $accountId:ID! $removeSecondaryGcpVSocketInput:RemoveSecondaryGcpVSocketInput!) {
	sites ( accountId:$accountId ) {
		removeSecondaryGcpVSocket ( input:$removeSecondaryGcpVSocketInput  )  {
			socketInfo {
				site {
					id
					name
				}
				id
				interfaceIp
				loadBalancerIp
			}
		}
	}	
}