mutation policyRemotePortFwdUpdateSection ( $policyUpdateSectionInput:PolicyUpdateSectionInput! $accountId:ID! ) {
  policy ( accountId:$accountId  ) {
    remotePortFwd  {
      updateSection ( input:$policyUpdateSectionInput   )  {
        section  {
          audit  {
            updatedTime 
            updatedBy 
          }
          section  {
            id 
            name 
          }
          properties
        }

        status 
        errors  {
          errorMessage
          errorCode
        }

      }
    }

  }  
}
