mutation ztnaAppConnectorUpdateZtnaAppConnectorsConfiguration ( $accountId:ID! $updateZtnaAppConnectorsConfigurationInput:UpdateZtnaAppConnectorsConfigurationInput!) {
	ztnaAppConnector ( accountId:$accountId ) {
		updateZtnaAppConnectorsConfiguration ( input:$updateZtnaAppConnectorsConfigurationInput  )  {
			ztnaAppConnectorsConfiguration {
				privateAppsServiceRange
				appConnectorManagementRange
			}
		}
	}	
}