mutation sitesRemoveSecondaryKvmVSocket ( $accountId:ID! $removeSecondaryKvmVSocketInput:RemoveSecondaryKvmVSocketInput!) {
	sites ( accountId:$accountId ) {
		removeSecondaryKvmVSocket ( input:$removeSecondaryKvmVSocketInput  )  {
			id
		}
	}	
}