mutation userDisableUser ( $accountId:ID! $disableUserInput:DisableUserInput!) {
	user ( accountId:$accountId ) {
		disableUser ( input:$disableUserInput  )  {
			users {
				id
				userId
				objectId
				onPremSid
				firstName
				lastName
				userPrincipalName
				displayName
				phone
				email
				department
				jobTitle
				userStatus
				creationDate
				lastModified
				importType
				userImportType
				directoryId
				hasRemoteAccessEligibility
				authInfo {
					authMethod
					authStatus
				}
				riskScore
			}
		}
	}	
}