mutation notificationDeleteMailingList ( $accountId:ID! $mailingListRefInput:MailingListRefInput!) {
	notification ( accountId:$accountId ) {
		deleteMailingList ( input:$mailingListRefInput  )  {
			mailingList {
				id
				name
				type
				address
				admin {
					id
					name
				}
				audit {
					updatedTime
					updatedBy {
						id
						name
					}
				}
			}
		}
	}	
}