mutation sitesUpdateBgpPeer ( $updateBgpPeerInput:UpdateBgpPeerInput! $accountId:ID! ) { sites ( accountId:$accountId ) { updateBgpPeer ( input:$updateBgpPeerInput ) { bgpPeer { siteRefSite: site { id name } id name peerAsn catoAsn peerIp catoIp advertiseDefaultRoute advertiseAllRoutes advertiseSummaryRoutes bgpSummaryRouteSummaryRoute: summaryRoute { id route bgpCommunityCommunity: community { from to } } bgpDefaultActionDefaultAction: defaultAction performNat md5AuthKey metric holdTime keepaliveInterval bfdEnabled bfdSettingsBfdSettings: bfdSettings { transmitInterval receiveInterval multiplier } bgpTrackingTracking: tracking { id enabled alertFrequency subscriptionId } } } } }