mutation userUpdateDynamicUserGroupsConfiguration ( $accountId:ID! $updateDynamicUserGroupsConfigurationInput:UpdateDynamicUserGroupsConfigurationInput!) {
	user ( accountId:$accountId ) {
		updateDynamicUserGroupsConfiguration ( input:$updateDynamicUserGroupsConfigurationInput  )  {
			department {
				enabled
			}
		}
	}	
}