mutation policySocketBypassUpdateSection ( $accountId:ID! $socketBypassPolicyMutationInput:SocketBypassPolicyMutationInput $policyUpdateSectionInput:PolicyUpdateSectionInput!) {
	policy ( accountId:$accountId ) {
		socketBypass ( input:$socketBypassPolicyMutationInput  )  {
			updateSection ( input:$policyUpdateSectionInput   ) {
				section {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					section {
						id
						name
					}
					properties
				}
				status
				errors {
					errorMessage
					errorCode
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
			}
		}
	}	
}