mutation networkConfigDnsUpdateForwardingRule ( $accountId:ID! $networkConfigDnsUpdateForwardingRuleInput:NetworkConfigDnsUpdateForwardingRuleInput!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			updateForwardingRule ( input:$networkConfigDnsUpdateForwardingRuleInput   ) {
				forwardingRule {
					id
					domain
					server
				}
			}
		}
	}	
}