mutation sitesCreateStaticHostBulk ( $accountId:ID! $createStaticHostBulkInput:CreateStaticHostBulkInput!) {
	sites ( accountId:$accountId ) {
		createStaticHostBulk ( input:$createStaticHostBulkInput  )  {
			host {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}