mutation policyWanNetworkMoveSection ( $policyMoveSectionInput:PolicyMoveSectionInput! $accountId:ID! ) {
  policy ( accountId:$accountId  ) {
    wanNetwork  {
      moveSection ( input:$policyMoveSectionInput   )  {
        section  {
          audit  {
            updatedTime 
            updatedBy 
          }
          section  {
            id 
            name 
          }
          properties
        }

        status 
        errors  {
          errorMessage
          errorCode
        }

      }
    }

  }  
}