mutation policyApplicationControlCreatePolicyRevision(
  $policyCreateRevisionInput: PolicyCreateRevisionInput!
  $accountId: ID!
) {
  policy(accountId: $accountId) {
    applicationControl {
      createPolicyRevision(input: $policyCreateRevisionInput) {
        policy {
          enabled
          revision {
            id
            name
          }
        }
        status
        errors {
          errorMessage
          errorCode
        }
      }
    }
  }
}
