mutation ztnaAppConnectorRemoveZtnaAppConnectorBwLicense ($accountId: ID!, $removeZtnaAppConnectorBwLicenseInput: RemoveZtnaAppConnectorBwLicenseInput!) {
	ztnaAppConnector(accountId: $accountId) {
		removeZtnaAppConnectorBwLicense(input: $removeZtnaAppConnectorBwLicenseInput) {
			pooledBandwidthAllocation {
				allocationId
				licenseId
				bw
			}
		}
	}
}
