mutation siteRemoveCloudInterconnectPhysicalConnection ( $removeCloudInterconnectPhysicalConnectionInput:RemoveCloudInterconnectPhysicalConnectionInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		removeCloudInterconnectPhysicalConnection ( input:$removeCloudInterconnectPhysicalConnectionInput  )  {
			id
		}

	}
}
