mutation policyApplicationControlPublishPolicyRevision($accountId: ID!) {
  policy(accountId: $accountId) {
    applicationControl {
      publishPolicyRevision {
        policy {
          enabled
          revision {
            id
            name
          }
        }
        status
        errors {
          errorMessage
          errorCode
        }
      }
    }
  }
}
