mutation policyAppTenantRestrictionMoveRule(
  $policyMoveRuleInput: PolicyMoveRuleInput!
  $accountId: ID!
) {
  policy(accountId: $accountId) {
    appTenantRestriction {
      moveRule(input: $policyMoveRuleInput) {
        rule {
          rule {
            id
            index
            section {
              id
              name
            }
          }
        }
        status
        errors {
          errorMessage
          errorCode
        }
      }
    }
  }
}
