mutation licensingStartServiceTrial ($accountId: ID!, $licensingStartServiceTrialInput: LicensingStartServiceTrialInput!) {
	licensing(accountId: $accountId) {
		startServiceTrial(input: $licensingStartServiceTrialInput) {
			trial {
				expirationDate
				plan
				service
				startDate
				status
			}
		}
	}
}
