mutation sitesUpdateSocketInterfaces ( $accountId:ID! $updateSocketInterfacesInput:UpdateSocketInterfacesInput!) {
	sites ( accountId:$accountId ) {
		updateSocketInterfaces ( input:$updateSocketInterfacesInput  )  {
			siteId
			socketInterfaceId
		}
	}	
}