mutation policyTlsInspectUpdateSection ($policyUpdateSectionInput: PolicyUpdateSectionInput!, $accountId: ID!, $tlsInspectPolicyMutationInput: TlsInspectPolicyMutationInput) {
	policy(accountId: $accountId) {
		tlsInspect(input: $tlsInspectPolicyMutationInput) {
			updateSection(input: $policyUpdateSectionInput) {
				section {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					section {
						id
						name
					}
					properties
				}
				status
				errors {
					errorMessage
					errorCode
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
			}
		}
	}
}
