mutation policyRemotePortFwdRemoveSection ($policyRemoveSectionInput: PolicyRemoveSectionInput!, $accountId: ID!, $remotePortFwdPolicyMutationInput: RemotePortFwdPolicyMutationInput) {
	policy(accountId: $accountId) {
		remotePortFwd(input: $remotePortFwdPolicyMutationInput) {
			removeSection(input: $policyRemoveSectionInput) {
				section {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					section {
						id
						name
					}
					properties
				}
				status
				errors {
					errorMessage
					errorCode
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
			}
		}
	}
}
