mutation objectUpdateGlobalIpRangeBulk ( $accountId:ID! $updateGlobalIpRangeInput:[UpdateGlobalIpRangeInput!]!) {
	object ( accountId:$accountId ) {
		updateGlobalIpRangeBulk ( input:$updateGlobalIpRangeInput  )  {
			globalIpRange {
				id
				name
				description
				ipRange
				subnet
			}
		}
	}	
}