mutation sitesUpdateSiteBackhauling ( $accountId:ID! $updateSiteBackhaulingInput:UpdateSiteBackhaulingInput!) {
	sites ( accountId:$accountId ) {
		updateSiteBackhauling ( input:$updateSiteBackhaulingInput  )  {
			site {
				id
				name
			}
			useAsBackhaulingGW
			destination
			nextHopIP
			preferredSocketPort
		}
	}	
}