mutation businessPlatformCreateTrialAccount ( $accountId:ID! $businessPlatformCreateTrialAccountInput:BusinessPlatformCreateTrialAccountInput!) {
	businessPlatform ( accountId:$accountId ) {
		createTrialAccount ( input:$businessPlatformCreateTrialAccountInput  )  {
			account {
				id
				externalName
				account {
					id
					name
				}
				partner {
					id
					name
				}
				accountExternalName
				description
				plan
				expiresOn
				estimatedCloseDate
				contactFirstName
				contactLastName
				contactEmail
				companyWebsite
				country
				city
				state
				street
				postalCode
				cmaCreatedBy
				cmaCreatedAt
			}
		}
	}	
}