mutation policyDynamicIpAllocationAddRule ( $accountId:ID! $dynamicIpAllocationPolicyMutationInput:DynamicIpAllocationPolicyMutationInput $dynamicIpAllocationAddRuleInput:DynamicIpAllocationAddRuleInput!) {
	policy ( accountId:$accountId ) {
		dynamicIpAllocation ( input:$dynamicIpAllocationPolicyMutationInput  )  {
			addRule ( input:$dynamicIpAllocationAddRuleInput   ) {
				rule {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					rule {
						id
						name
						description
						index
						section {
							id
							name
						}
						enabled
						source {
							user {
								id
								name
							}
							usersGroup {
								id
								name
							}
						}
						platform
						country {
							id
							name
						}
						range {
							globalIpRange {
								id
								name
							}
						}
					}
					properties
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
				status
				errors {
					errorMessage
					errorCode
				}
			}
		}
	}	
}