mutation privateApplicationDeletePrivateApplication ( $accountId:ID! $deletePrivateApplicationInput:DeletePrivateApplicationInput!) {
	privateApplication ( accountId:$accountId ) {
		deletePrivateApplication ( input:$deletePrivateApplicationInput  )  {
			application
		}
	}	
}