mutation networkConfigDnsSetForwardingRule ($accountId: ID!, $networkConfigDnsSetForwardingRuleInput: NetworkConfigDnsSetForwardingRuleInput!) {
	networkConfig(accountId: $accountId) {
		dns {
			setForwardingRule(input: $networkConfigDnsSetForwardingRuleInput) {
				forwardingRule {
					id
					domain
					server
				}
			}
		}
	}
}
