mutation sitesAddSecondaryGcpVSocket ( $accountId:ID! $addSecondaryGcpVSocketInput:AddSecondaryGcpVSocketInput!) {
	sites ( accountId:$accountId ) {
		addSecondaryGcpVSocket ( input:$addSecondaryGcpVSocketInput  )  {
			socketInfo {
				site {
					id
					name
				}
				id
				interfaceIp
				loadBalancerIp
			}
		}
	}	
}