mutation siteUpdateNetworkRangeBulk ( $accountId:ID! $updateNetworkRangeBulkInput:UpdateNetworkRangeBulkInput!) {
	site ( accountId:$accountId ) {
		updateNetworkRangeBulk ( input:$updateNetworkRangeBulkInput  )  {
			networkRange {
				networkRangeId
				name
				rangeType
				subnet
				translatedSubnet
				localIp
				gateway
				vlan
				azureFloatingIp
				gcpLoadBalancerIp
				primaryManagementIp
				secondaryManagementIp
				dhcpSettings {
					dhcpType
					ipRange
					relayGroupId
					dhcpMicrosegmentation
				}
				mdnsReflector
				internetOnly
			}
		}
	}	
}