mutation policyWanNetworkMoveSection ( $accountId: ID! $policyMoveSectionInput:PolicyMoveSectionInput! $wanNetworkPolicyMutationInput:WanNetworkPolicyMutationInput ) {
	policy ( accountId: $accountId ) {
		wanNetwork ( input:$wanNetworkPolicyMutationInput  )  {
			moveSection ( input:$policyMoveSectionInput   ) {
				policySectionPayloadSection: section {
					audit {
						updatedTime
						updatedBy
					}
					section {
						id
						name
					}
					properties
				}

				policyMutationStatusStatus: status
				policyMutationErrorErrors: errors {
					errorMessage
					errorCode
				}

			}
		}

	}	
}