mutation siteRemoveSecondaryKvmVSocket ( $accountId:ID! $removeSecondaryKvmVSocketInput:RemoveSecondaryKvmVSocketInput!) {
	site ( accountId:$accountId ) {
		removeSecondaryKvmVSocket ( input:$removeSecondaryKvmVSocketInput  )  {
			id
		}
	}	
}