mutation notificationDeleteSubscriptionGroup ( $accountId:ID! $subscriptionGroupRefInput:SubscriptionGroupRefInput!) {
	notification ( accountId:$accountId ) {
		deleteSubscriptionGroup ( input:$subscriptionGroupRefInput  )  {
			subscriptionGroup {
				id
				name
				mailingList {
					id
					name
					type
					address
					admin {
						id
						name
					}
					audit {
						updatedTime
						updatedBy {
							id
							name
							... on AdminRef {
								id
								name
							}
							... on ApiKeyRef {
								id
								name
							}
						}
					}
				}
				integration {
					webhookList {
						id
						name
						enabled
						url
						requestMethod
						auth {
							authType
							... on BearerTokenAuth {
								authType
							}
							... on BasicAuth {
								authType
								username
							}
							... on CustomHeaderAuth {
								authType
								name
							}
							... on CustomHeadersAuth {
								authType
								plainHeaders {
									name
									value
								}
								secretHeaders {
									name
								}
							}
							... on NoAuth {
								authType
							}
						}
						header {
							name
							value
						}
						body
						responseMapping {
							key
							value
						}
						relatedWebhookId
					}
				}
			}
		}
	}	
}