mutation siteDeleteStaticHostBulk ( $accountId:ID! $deleteStaticHostBulkInput:DeleteStaticHostBulkInput!) {
	site ( accountId:$accountId ) {
		deleteStaticHostBulk ( input:$deleteStaticHostBulkInput  )  {
			host {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}