mutation policySocketBypassRemoveSection ( $accountId:ID! $socketBypassPolicyMutationInput:SocketBypassPolicyMutationInput $policyRemoveSectionInput:PolicyRemoveSectionInput!) {
	policy ( accountId:$accountId ) {
		socketBypass ( input:$socketBypassPolicyMutationInput  )  {
			removeSection ( input:$policyRemoveSectionInput   ) {
				section {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					section {
						id
						name
					}
					properties
				}
				status
				errors {
					errorMessage
					errorCode
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
			}
		}
	}	
}