mutation policyZtnaAlwaysOnUpdateRule ( $accountId:ID! $ztnaAlwaysOnPolicyMutationInput:ZtnaAlwaysOnPolicyMutationInput $ztnaAlwaysOnUpdateRuleInput:ZtnaAlwaysOnUpdateRuleInput!) {
	policy ( accountId:$accountId ) {
		ztnaAlwaysOn ( input:$ztnaAlwaysOnPolicyMutationInput  )  {
			updateRule ( input:$ztnaAlwaysOnUpdateRuleInput   ) {
				rule {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					rule {
						id
						name
						description
						index
						section {
							id
							name
						}
						enabled
						source {
							user {
								id
								name
							}
							usersGroup {
								id
								name
							}
						}
						platform
						devicePostureProfile {
							id
							name
						}
						action
						allowUserBypass
						bypassDuration {
							time
							unit
						}
						allowFailOpen
						antiTamperMode
					}
					properties
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
				status
				errors {
					errorMessage
					errorCode
				}
			}
		}
	}	
}