mutation ztnaAppConnectorAddZtnaAppConnectorBwLicense ($accountId: ID!, $addZtnaAppConnectorBwLicenseInput: AddZtnaAppConnectorBwLicenseInput!) {
	ztnaAppConnector(accountId: $accountId) {
		addZtnaAppConnectorBwLicense(input: $addZtnaAppConnectorBwLicenseInput) {
			pooledBandwidthAllocation {
				allocationId
				licenseId
				bw
			}
		}
	}
}
