mutation siteUpdateSiteSocketConfiguration ( $accountId:ID! $updateSiteSocketConfigurationInput:UpdateSiteSocketConfigurationInput!) {
	site ( accountId:$accountId ) {
		updateSiteSocketConfiguration ( input:$updateSiteSocketConfigurationInput  )  {
			siteSocketConfiguration {
				primarySocketConfiguration {
					description
				}
				secondarySocketConfiguration {
					description
				}
			}
		}
	}	
}