mutation networkConfigDhcpSetRelayGroup ( $accountId:ID! $networkConfigDhcpSetRelayGroupInput:NetworkConfigDhcpSetRelayGroupInput!) {
	networkConfig ( accountId:$accountId ) {
		dhcp {
			setRelayGroup ( input:$networkConfigDhcpSetRelayGroupInput   ) {
				relayGroup {
					id
					name
					server
				}
			}
		}
	}	
}