mutation licensingEnableServiceForManagedAccount ( $accountId:ID! $enableServiceForManagedAccountInput:EnableServiceForManagedAccountInput!) {
	licensing ( accountId:$accountId ) {
		enableServiceForManagedAccount ( input:$enableServiceForManagedAccountInput  )  {
			isSuccess
		}
	}	
}