mutation networkConfigDhcpCreateRelayGroup ( $accountId:ID! $networkConfigDhcpCreateRelayGroupInput:NetworkConfigDhcpCreateRelayGroupInput!) {
	networkConfig ( accountId:$accountId ) {
		dhcp {
			createRelayGroup ( input:$networkConfigDhcpCreateRelayGroupInput   ) {
				relayGroup {
					id
					name
					server
				}
			}
		}
	}
}