mutation sitesUpdateWifiRadioProfile ( $accountId:ID! $updateWifiRadioProfileInput:UpdateWifiRadioProfileInput!) {
	sites ( accountId:$accountId ) {
		updateWifiRadioProfile ( input:$updateWifiRadioProfileInput  )  {
			wifiRadioProfile {
				id
				site {
					id
					name
				}
				band24 {
					band
					standard
					channelWidth
					dfsEnabled
					channel
				}
				band5 {
					band
					standard
					channelWidth
					dfsEnabled
					channel
				}
			}
		}
	}	
}