mutation siteUpdateSecondaryGcpVSocket ( $accountId:ID! $updateSecondaryGcpVSocketInput:UpdateSecondaryGcpVSocketInput!) {
	site ( accountId:$accountId ) {
		updateSecondaryGcpVSocket ( input:$updateSecondaryGcpVSocketInput  )  {
			socketInfo {
				site {
					id
					name
				}
				id
				interfaceIp
				loadBalancerIp
			}
		}
	}	
}