mutation objectDeleteGlobalIpRangeBulk ($accountID: ID!, $input: [GlobalIpRangeRefInput!]!) {
	object(accountId: $accountID) {
		deleteGlobalIpRangeBulk(input: $input) {
			globalIpRange {
				id
				name
				description
				ipRange
				subnet
			}
		}
	}
}
