mutation siteAddSecondaryKvmVSocket ( $accountId:ID! $addSecondaryKvmVSocketInput:AddSecondaryKvmVSocketInput!) {
	site ( accountId:$accountId ) {
		addSecondaryKvmVSocket ( input:$addSecondaryKvmVSocketInput  )  {
			id
		}
	}	
}