mutation networkConfigDnsDeleteSuffixSet ($accountId: ID!, $networkConfigDnsDeleteSuffixSetInput: NetworkConfigDnsDeleteSuffixSetInput!) {
	networkConfig(accountId: $accountId) {
		dns {
			deleteSuffixSet(input: $networkConfigDnsDeleteSuffixSetInput) {
				dnsSuffixSet {
					id
					name
					suffix
					audit {
						updatedTime
						updatedBy {
							id
							name
						}
					}
				}
			}
		}
	}
}
