mutation policyClientConnectivityRemoveRule ( $accountId:ID! $clientConnectivityPolicyMutationInput:ClientConnectivityPolicyMutationInput $clientConnectivityRemoveRuleInput:ClientConnectivityRemoveRuleInput!) {
	policy ( accountId:$accountId ) {
		clientConnectivity ( input:$clientConnectivityPolicyMutationInput  )  {
			removeRule ( input:$clientConnectivityRemoveRuleInput   ) {
				rule {
					audit {
						updatedTime
						updatedBy
					}
					metadata {
						lock {
							lockingAdminEmail
							lockingTime
							lockingRevisionId
						}
					}
					rule {
						id
						name
						description
						index
						section {
							id
							name
						}
						enabled
						source {
							user {
								id
								name
							}
							usersGroup {
								id
								name
							}
						}
						confidenceLevel
						platform
						country {
							id
							name
						}
						sourceRange {
							globalIpRange {
								id
								name
							}
						}
						device {
							id
							name
						}
						connectionOrigin
						action
					}
					properties
				}
				revision {
					id
					name
					description
					changes
					createdTime
					updatedTime
				}
				status
				errors {
					errorMessage
					errorCode
				}
			}
		}
	}	
}