mutation siteExchangeSocketPorts ( $accountId:ID! $exchangeSocketPortsInput:ExchangeSocketPortsInput!) {
	site ( accountId:$accountId ) {
		exchangeSocketPorts ( input:$exchangeSocketPortsInput  )  {
			interfaces {
				interfaceId
				name
			}
		}
	}	
}