mutation policyWanFirewallPublishPolicyRevision ( $policyPublishRevisionInput:PolicyPublishRevisionInput $accountId:ID! ) {
	policy ( accountId:$accountId  ) {
		wanFirewall  {
			publishPolicyRevision ( input:$policyPublishRevisionInput   ) {
				status 
				errors  {
					errorMessage
					errorCode
				}

			}
		}

	}	
}
