mutation sitesUpdateStaticHostBulk ( $accountId:ID! $updateStaticHostBulkInput:UpdateStaticHostBulkInput!) {
	sites ( accountId:$accountId ) {
		updateStaticHostBulk ( input:$updateStaticHostBulkInput  )  {
			host {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}