mutation ztnaAppConnectorUpgradeZtnaAppConnector ( $accountId:ID! $upgradeZtnaAppConnectorInput:UpgradeZtnaAppConnectorInput!) {
	ztnaAppConnector ( accountId:$accountId ) {
		upgradeZtnaAppConnector ( input:$upgradeZtnaAppConnectorInput  )  {
			upgrades {
				ztnaAppConnector {
					id
					name
				}
				targetVersion
			}
		}
	}	
}