mutation policyWanNetworkPublishPolicyRevision ( $accountId: ID! $policyPublishRevisionInput:PolicyPublishRevisionInput $wanNetworkPolicyMutationInput:WanNetworkPolicyMutationInput ) {
	policy ( accountId: $accountId ) {
		wanNetwork ( input:$wanNetworkPolicyMutationInput  )  {
			publishPolicyRevision ( input:$policyPublishRevisionInput   ) {
				wanNetworkPolicyPolicy: policy {
					enabled
					rules {
						policyElementAuditAudit: audit {
							updatedTime
							updatedBy
						}

						wanNetworkRuleRule: rule {
							id
							name
							description
							index
							policySectionInfoSection: section {
								id
								name
							}
							enabled
							wanNetworkRuleTypeRuleType: ruleType
							wanNetworkRuleRouteTypeRouteType: routeType
							wanNetworkRuleSourceSource: source {
								userRefUser: user {
									id
									name
								}

								floatingSubnetRefFloatingSubnet: floatingSubnet {
									id
									name
								}

								globalIpRangeRefGlobalIpRange: globalIpRange {
									id
									name
								}

								groupRefGroup: group {
									id
									name
								}

								hostRefHost: host {
									id
									name
								}

								ip
								ipAddressRangeIpRange: ipRange {
									from
									to
								}

								networkInterfaceRefNetworkInterface: networkInterface {
									id
									name
								}

								subnet
								siteRefSite: site {
									id
									name
								}

								siteNetworkSubnetRefSiteNetworkSubnet: siteNetworkSubnet {
									id
									name
								}

								systemGroupRefSystemGroup: systemGroup {
									id
									name
								}

								usersGroupRefUsersGroup: usersGroup {
									id
									name
								}

							}
							wanNetworkRuleDestinationDestination: destination {
								userRefUser: user {
									id
									name
								}

								floatingSubnetRefFloatingSubnet: floatingSubnet {
									id
									name
								}

								globalIpRangeRefGlobalIpRange: globalIpRange {
									id
									name
								}

								groupRefGroup: group {
									id
									name
								}

								hostRefHost: host {
									id
									name
								}

								ip
								ipAddressRangeIpRange: ipRange {
									from
									to
								}

								networkInterfaceRefNetworkInterface: networkInterface {
									id
									name
								}

								subnet
								siteRefSite: site {
									id
									name
								}

								siteNetworkSubnetRefSiteNetworkSubnet: siteNetworkSubnet {
									id
									name
								}

								systemGroupRefSystemGroup: systemGroup {
									id
									name
								}

								usersGroupRefUsersGroup: usersGroup {
									id
									name
								}

							}
							wanNetworkRuleApplicationApplication: application {
								applicationRefApplication: application {
									id
									name
								}

								applicationCategoryRefAppCategory: appCategory {
									id
									name
								}

								customApplicationRefCustomApp: customApp {
									id
									name
								}

								customCategoryRefCustomCategory: customCategory {
									id
									name
								}

								customServiceIpCustomServiceIp: customServiceIp {
									name
									ip
									ipAddressRangeIpRange: ipRange {
										from
										to
									}
								}

								customServiceCustomService: customService {
									port
									portRangePortRange: portRange {
										from
										to
									}
									ipProtocolProtocol: protocol
								}

								domain
								fqdn
								serviceRefService: service {
									id
									name
								}

							}
							wanNetworkRuleConfigurationConfiguration: configuration {
								activeTcpAcceleration
								packetLossMitigation
								preserveSourcePort
								wanNetworkRuleTransportPrimaryTransport: primaryTransport {
									wanNetworkRuleTransportTypeTransportType: transportType
									wanNetworkRuleInterfaceRolePrimaryInterfaceRole: primaryInterfaceRole
									wanNetworkRuleInterfaceRoleSecondaryInterfaceRole: secondaryInterfaceRole
								}

								wanNetworkRuleTransportSecondaryTransport: secondaryTransport {
									wanNetworkRuleTransportTypeTransportType: transportType
									wanNetworkRuleInterfaceRolePrimaryInterfaceRole: primaryInterfaceRole
									wanNetworkRuleInterfaceRoleSecondaryInterfaceRole: secondaryInterfaceRole
								}

								allocatedIpRefAllocationIp: allocationIp {
									id
									name
								}

								popLocationRefPopLocation: popLocation {
									id
									name
								}

								siteRefBackhaulingSite: backhaulingSite {
									id
									name
								}

							}
							bandwidthManagementRefBandwidthPriority: bandwidthPriority {
								id
								name
							}
							wanNetworkRuleExceptionExceptions: exceptions {
								name
								wanNetworkRuleSourceSource: source {
									userRefUser: user {
										id
										name
									}
									floatingSubnetRefFloatingSubnet: floatingSubnet {
										id
										name
									}
									globalIpRangeRefGlobalIpRange: globalIpRange {
										id
										name
									}
									groupRefGroup: group {
										id
										name
									}
									hostRefHost: host {
										id
										name
									}
									ip
									ipAddressRangeIpRange: ipRange {
										from
										to
									}
									networkInterfaceRefNetworkInterface: networkInterface {
										id
										name
									}
									subnet
									siteRefSite: site {
										id
										name
									}
									siteNetworkSubnetRefSiteNetworkSubnet: siteNetworkSubnet {
										id
										name
									}
									systemGroupRefSystemGroup: systemGroup {
										id
										name
									}
									usersGroupRefUsersGroup: usersGroup {
										id
										name
									}
								}

								wanNetworkRuleDestinationDestination: destination {
									userRefUser: user {
										id
										name
									}
									floatingSubnetRefFloatingSubnet: floatingSubnet {
										id
										name
									}
									globalIpRangeRefGlobalIpRange: globalIpRange {
										id
										name
									}
									groupRefGroup: group {
										id
										name
									}
									hostRefHost: host {
										id
										name
									}
									ip
									ipAddressRangeIpRange: ipRange {
										from
										to
									}
									networkInterfaceRefNetworkInterface: networkInterface {
										id
										name
									}
									subnet
									siteRefSite: site {
										id
										name
									}
									siteNetworkSubnetRefSiteNetworkSubnet: siteNetworkSubnet {
										id
										name
									}
									systemGroupRefSystemGroup: systemGroup {
										id
										name
									}
									usersGroupRefUsersGroup: usersGroup {
										id
										name
									}
								}

								wanNetworkRuleApplicationApplication: application {
									applicationRefApplication: application {
										id
										name
									}
									applicationCategoryRefAppCategory: appCategory {
										id
										name
									}
									customApplicationRefCustomApp: customApp {
										id
										name
									}
									customCategoryRefCustomCategory: customCategory {
										id
										name
									}
									customServiceIpCustomServiceIp: customServiceIp {
										name
										ip
										ipAddressRangeIpRange: ipRange {
											from
											to
										}

									}
									customServiceCustomService: customService {
										port
										portRangePortRange: portRange {
											from
											to
										}

										ipProtocolProtocol: protocol
									}
									domain
									fqdn
									serviceRefService: service {
										id
										name
									}
								}

							}
						}

						policyElementPropertiesEnumProperties: properties
					}
					sections {
						policyElementAuditAudit: audit {
							updatedTime
							updatedBy
						}

						policySectionInfoSection: section {
							id
							name
						}

						policyElementPropertiesEnumProperties: properties
					}
					audit {
						publishedTime
						publishedBy
					}
					revision {
						id
						name
						description
						changes
						createdTime
						updatedTime
					}
				}

				policyMutationStatusStatus: status
				policyMutationErrorErrors: errors {
					errorMessage
					errorCode
				}

			}
		}

	}	
}