mutation sitesUpdateWifiSsid ( $accountId:ID! $updateWifiSsidInput:UpdateWifiSsidInput!) {
	sites ( accountId:$accountId ) {
		updateWifiSsid ( input:$updateWifiSsidInput  )  {
			wifiSsid {
				id
				networkInterfaceId
				site {
					id
					name
				}
				name
				enabled
				category
				visible
				subnet
				localIp
				dhcp {
					dhcpSubnet
				}
				vlanId
				dhcpEnabled
				microsegmentationEnabled
				internetOnly
				mdnsEnabled
				security {
					mode
					authProtocol
					trackAuthentication
				}
				band
			}
		}
	}	
}