mutation xdrAnalystFeedback($accountId: ID!, $analystFeedbackInput: AnalystFeedbackInput!) {
  xdr(accountId: $accountId) {
    analystFeedback(input: $analystFeedbackInput) {
      story {
        id
      }
    }
  }
}
