mutation siteAddCloudInterconnectSite ( $addCloudInterconnectSiteInput:AddCloudInterconnectSiteInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		addCloudInterconnectSite ( input:$addCloudInterconnectSiteInput  )  {
			siteId
		}

	}
}
