mutation xdrAddStoryComment ( $accountId:ID! $addStoryCommentInput:AddStoryCommentInput!) {
	xdr ( accountId:$accountId ) {
		addStoryComment ( input:$addStoryCommentInput  )  {
			comment {
				id
				createdAt
				text
				actor {
					id
					name
				}
				type
				author
			}
		}
	}	
}