mutation networkConfigDnsCreateSuffixSet ($accountId: ID!, $networkConfigDnsCreateSuffixSetInput: NetworkConfigDnsCreateSuffixSetInput!) {
	networkConfig(accountId: $accountId) {
		dns {
			createSuffixSet(input: $networkConfigDnsCreateSuffixSetInput) {
				dnsSuffixSet {
					id
					name
					suffix
					audit {
						updatedTime
						updatedBy {
							id
							name
						}
					}
				}
			}
		}
	}
}
