mutation policyAppTenantRestrictionUpdatePolicy(
  $appTenantRestrictionPolicyUpdateInput: AppTenantRestrictionPolicyUpdateInput!
  $accountId: ID!
) {
  policy(accountId: $accountId) {
    appTenantRestriction {
      updatePolicy(input: $appTenantRestrictionPolicyUpdateInput) {
        policy {
          enabled
        }
        status
        errors {
          errorMessage
          errorCode
        }
      }
    }
  }
}
