mutation siteAddCloudInterconnectPhysicalConnection ( $addCloudInterconnectPhysicalConnectionInput:AddCloudInterconnectPhysicalConnectionInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		addCloudInterconnectPhysicalConnection ( input:$addCloudInterconnectPhysicalConnectionInput  )  {
			id
		}

	}
}
