mutation xdrDeleteStoryComment ( $accountId:ID! $deleteStoryCommentInput:DeleteStoryCommentInput!) {
	xdr ( accountId:$accountId ) {
		deleteStoryComment ( input:$deleteStoryCommentInput  )  {
			comment {
				id
				createdAt
				text
				actor {
					id
					name
				}
				type
				author
			}
		}
	}	
}