mutation licensingDisableServiceForManagedAccount ( $accountId:ID! $disableServiceForManagedAccountInput:DisableServiceForManagedAccountInput!) {
	licensing ( accountId:$accountId ) {
		disableServiceForManagedAccount ( input:$disableServiceForManagedAccountInput  )  {
			isSuccess
		}
	}	
}