mutation userRevokeUserSession ( $accountId:ID! $revokeUserSessionInput:RevokeUserSessionInput!) {
	user ( accountId:$accountId ) {
		revokeUserSession ( input:$revokeUserSessionInput  )  {
			status
		}
	}	
}