mutation objectCreateGlobalIpRangeBulk ( $accountId:ID! $createGlobalIpRangeInput:[CreateGlobalIpRangeInput!]!) {
	object ( accountId:$accountId ) {
		createGlobalIpRangeBulk ( input:$createGlobalIpRangeInput  )  {
			globalIpRange {
				id
				name
				description
				ipRange
				subnet
			}
		}
	}	
}