mutation networkConfigDhcpDeleteRelayGroup ($accountId: ID!, $networkConfigDhcpDeleteRelayGroupInput: NetworkConfigDhcpDeleteRelayGroupInput!) {
	networkConfig(accountId: $accountId) {
		dhcp {
			deleteRelayGroup(input: $networkConfigDhcpDeleteRelayGroupInput) {
				relayGroup {
					id
					name
					server
				}
			}
		}
	}
}
