mutation sitesUpdateSiteStaticHosts ( $accountId:ID! $updateSiteStaticHostsInput:UpdateSiteStaticHostsInput!) {
	sites ( accountId:$accountId ) {
		updateSiteStaticHosts ( input:$updateSiteStaticHostsInput  )  {
			host {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}