mutation networkConfigDnsDeleteForwardingRule ($accountId: ID!, $networkConfigDnsDeleteForwardingRuleInput: NetworkConfigDnsDeleteForwardingRuleInput!) {
	networkConfig(accountId: $accountId) {
		dns {
			deleteForwardingRule(input: $networkConfigDnsDeleteForwardingRuleInput) {
				forwardingRule {
					id
					domain
					server
				}
			}
		}
	}
}
