mutation networkConfigDnsSetSuffixSet ( $accountId:ID! $networkConfigDnsSetSuffixSetInput:NetworkConfigDnsSetSuffixSetInput!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			setSuffixSet ( input:$networkConfigDnsSetSuffixSetInput   ) {
				dnsSuffixSet {
					id
					name
					suffix
					audit {
						updatedTime
						updatedBy {
							id
							name
						}
					}
				}
			}
		}
	}	
}