mutation sitesCreateNetworkRangeBulk ( $accountId:ID! $createNetworkRangeBulkInput:CreateNetworkRangeBulkInput!) {
	sites ( accountId:$accountId ) {
		createNetworkRangeBulk ( input:$createNetworkRangeBulkInput  )  {
			networkRange {
				networkRangeId
				name
				rangeType
				subnet
				translatedSubnet
				localIp
				gateway
				vlan
				azureFloatingIp
				gcpLoadBalancerIp
				primaryManagementIp
				secondaryManagementIp
				dhcpSettings {
					dhcpType
					ipRange
					relayGroupId
					dhcpMicrosegmentation
				}
				mdnsReflector
				internetOnly
			}
		}
	}	
}