mutation networkConfigDnsCreateForwardingRule ( $accountId:ID! $networkConfigDnsCreateForwardingRuleInput:NetworkConfigDnsCreateForwardingRuleInput!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			createForwardingRule ( input:$networkConfigDnsCreateForwardingRuleInput   ) {
				forwardingRule {
					id
					domain
					server
				}
			}
		}
	}	
}