mutation siteUpdateCloudInterconnectPhysicalConnection ( $updateCloudInterconnectPhysicalConnectionInput:UpdateCloudInterconnectPhysicalConnectionInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		updateCloudInterconnectPhysicalConnection ( input:$updateCloudInterconnectPhysicalConnectionInput  )  {
			id
		}

	}
}
