mutation customAppDataUpdateCustomApplication ( $accountId:ID! $updateCustomApplicationInput:UpdateCustomApplicationInput!) {
	customAppData ( accountId:$accountId ) {
		updateCustomApplication ( input:$updateCustomApplicationInput  )  {
			customApplication {
				id
				name
				description
				category {
					id
					name
				}
				criteria {
					protocol
					port
					portRange {
						from
						to
					}
					destination {
						domain
						fqdn
						destinationIp {
							ip
							subnet
							ipRange {
								from
								to
							}
						}
					}
				}
			}
		}
	}	
}