mutation licensingStartServiceTrial ($accountId: ID!, $licensingStartServiceTrialInput: LicensingStartServiceTrialInput!) {
	licensing(accountId: $accountId) {
		startServiceTrial(input: $licensingStartServiceTrialInput) {
			trial {
				service
				plan
				status
				startDate
				expirationDate
			}
		}
	}
}
