mutation networkConfigDhcpUpdateRelayGroup ($accountId: ID!, $networkConfigDhcpUpdateRelayGroupInput: NetworkConfigDhcpUpdateRelayGroupInput!) {
	networkConfig(accountId: $accountId) {
		dhcp {
			updateRelayGroup(input: $networkConfigDhcpUpdateRelayGroupInput) {
				relayGroup {
					id
					name
					server
				}
			}
		}
	}
}
