mutation policyInternetFirewallPublishPolicyRevision ( $internetFirewallPolicyMutationInput:InternetFirewallPolicyMutationInput $policyPublishRevisionInput:PolicyPublishRevisionInput $accountId:ID! ) {
	policy ( accountId:$accountId  ) {
		internetFirewall ( input:$internetFirewallPolicyMutationInput  )  {
			publishPolicyRevision ( input:$policyPublishRevisionInput   ) {
				status 
				errors  {
					errorMessage
					errorCode
				}

			}
		}

	}	
}
