query catalogsCatalogApplicationList ( $accountId:ID! $catalogApplicationListInput:CatalogApplicationListInput!) {
	catalogs ( accountId:$accountId ) {
		catalogApplicationList ( input:$catalogApplicationListInput  )  {
			application {
				id
				name
				descriptionSummary
				description
				category {
					id
					name
				}
				complianceAttributes {
					iso27001
					sox
					hippa
					soc1
					soc2
					soc3
					isae3402
					pciDss
					c5Attestation
					cyberEssentialsPlusUk
					cjis
					cobit
					coppa
					csaStar
					fedRamp
					ferpa
					ffiec
					finra
					fisma
					gapp
					gdpr
					glba
					hitrustCsf
					iso27002
					iso27017
					iso27018
					iso9000
					iso9001
					itar
					jerichoForumCommandments
					nistSp80053
					euUsDataPrivacyFramework
					japanPrivacyMark
					trustArcPrivacy
				}
				securityAttributes {
					mfa
					encryptionAtRest
					auditTrail
					rbac
					rememberPassword
					sso
					trustedCertificate
					tlsEnforcement
					httpSecurityHeaders
					dataRetentionPolicy
					dataDeletionPolicy
					dataOwnership
					encryptionStrengthAtRest
					weakCipherSupport
					tlsVersionSupport
					termsOfUseCustomerProtectionUrl
					privacyPolicyUrl
					physicalDataCenterSecurity
					disasterRecovery
					encryptionInTransit
					dataSegregatedByTenant
				}
				identityAccessManagementAttributes {
					accessControlEnforcement
					ipBasedAccessRestrictions
					samlAuthentication
				}
				ipoStatus
				website
				originCountry {
					id
					name
				}
				region
				city
				risk
				numOfEmployees
				capability
				activity {
					id
					name
					fields {
						id
						name
						possibleOperators
						possibleValues
					}
				}
				tenantActivity {
					id
					name
					fields {
						id
						name
						possibleOperators
						possibleValues
					}
				}
				type
				sanctioned
				recentlyAdded
				standardPorts {
					port
					portRange {
						from
						to
					}
					protocol
				}
				aiSecurity {
					risk
					scope
					dataUsagePolicy {
						type
						description
						reference
						referenceType
						referenceUrl
					}
				}
				parentApp {
					id
					name
				}
				childApp {
					id
					name
				}
				fqdn
			}
			pageInfo {
				total
			}
		}
	}	
}