query networkRangeList($accountID: ID!, $input: NetworkRangeListInput!) {
  site(accountId: $accountID) {
    networkRangeList(input: $input) {
      items {
        azureFloatingIp
        dhcpSettings {
          dhcpMicrosegmentation
          dhcpType
          ipRange
          leaseTimeSettings {
            leaseTime
            timeUnit
          }
          relayGroupId
        }
        gateway
        gcpLoadBalancerIp
        internetOnly
        localIp
        mdnsReflector
        name
        networkRangeId
        primaryManagementIp
        rangeType
        secondaryManagementIp
        subnet
        translatedSubnet
        vlan
      }
      total
    }
  }
}

