query siteStaticHost ( $accountId:ID! $siteRefInput:SiteRefInput! $hostId:ID!) {
	site ( accountId:$accountId ) {
		staticHost ( site:$siteRefInput  hostId:$hostId  )  {
			host {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}