query ztnaAppConnectorZtnaAppConnectorGroupList ( $accountId:ID! $ztnaAppConnectorGroupListInput:ZtnaAppConnectorGroupListInput) {
	ztnaAppConnector ( accountId:$accountId ) {
		ztnaAppConnectorGroupList ( input:$ztnaAppConnectorGroupListInput  )  {
			items
			pageInfo {
				total
			}
		}
	}	
}