query siteSecondaryGcpVSocket ( $accountId:ID! $secondaryGcpVSocketInput:SecondaryGcpVSocketInput!) {
	site ( accountId:$accountId ) {
		secondaryGcpVSocket ( input:$secondaryGcpVSocketInput  )  {
			socketInfo {
				site {
					id
					name
				}
				id
				interfaceIp
				loadBalancerIp
			}
		}
	}	
}