query appConnectorReadConnector($accountId: ID!, $ref: ZtnaAppConnectorRefInput!) {
  ztnaAppConnector(accountId: $accountId) {
    ztnaAppConnector(input: $ref) {
      id
      name
      serialNumber
      type
      groupName
      address {
        addressValidated
        cityName
        country {
          id
          name
        }
        stateName
        street
        zipCode
      }
      timezone
      preferredPopLocation {
        preferredOnly
        automatic
        primary {
          id
          name
        }
        secondary {
          id
          name
        }
      }
      privateAppRef {
        id
        name
      }
    }
  }
}
