query siteValidWifiRadioSettingsByCountry ( $accountId:ID! $validWifiRadioSettingsByCountryInput:ValidWifiRadioSettingsByCountryInput!) {
	site ( accountId:$accountId ) {
		validWifiRadioSettingsByCountry ( input:$validWifiRadioSettingsByCountryInput  )  {
			band24 {
				standards
				channelWidths
				channels
			}
			band5 {
				standards
				channelWidths
				channels
			}
		}
	}	
}