query popLocations ( $accountId:ID! $popLocationFilterInput:PopLocationFilterInput $popLocationAllocatedIpInput:PopLocationAllocatedIpInput $id:ID!) {
	popLocations ( accountId:$accountId ) {
		popLocationList ( input:$popLocationFilterInput  )  {
			items {
				id
				name
				displayName
				country {
					id
					name
				}
				isPrivate
				cloudInterconnect {
					taggingMethod
					providerName
				}
			}
		}
		allocatedIpList ( input:$popLocationAllocatedIpInput  )  {
			allocatedIp {
				id
				account {
					id
					name
				}
				ip
				popLocation {
					id
					name
				}
				allocationType
				description
				subnet
				state
			}
			paging {
				total
			}
		}
		bgpProfile ( id:$id  )  {
			id
			name
			description
			communities {
				from
				to
			}
			createdAt
			lastUpdatedAt
		}
		bgpProfileList {
			items {
				id
				name
				description
				communities {
					from
					to
				}
				createdAt
				lastUpdatedAt
			}
		}
	}	
}