query appStats ($limit: Int, $from: Int, $accountID: ID!, $timeFrame: TimeFrame!, $measures: [Measure], $dimensions: [Dimension], $filters: [AppStatsFilter!], $sort: [AppStatsSort!], $appStatsPostAggFilter: [AppStatsPostAggFilter!], $includeEmptyDimension: Boolean) {
	appStats(accountID: $accountID, timeFrame: $timeFrame, measures: $measures, dimensions: $dimensions, filters: $filters, postAggFilters: $appStatsPostAggFilter, sort: $sort, includeEmptyDimension: $includeEmptyDimension) {
		id
		from
		to
		total
		totals
		records(limit: $limit, from: $from) {
			fieldsUnitTypes
			fieldsMap
			trends
			prevTimeFrame
			flatFields
		}
	}
}
