query rbacRoleManagementRoleList($accountId: ID!, $input: RoleManagementRoleListInput!) {
  rbac(accountId: $accountId) {
    roleManagement {
      roleList(input: $input) { items { id name description predefined isUsedOnExternalAccess accountType permission { resource action } } paging { total } }
    }
  }
}
