query networkConfigDnsSiteSettings ($accountId: ID!, $siteRefInput: SiteRefInput!) {
	networkConfig(accountId: $accountId) {
		dns {
			siteSettings(site: $siteRefInput) {
				siteId
				primaryServer
				secondaryServer
				suffix
			}
		}
	}
}
