query siteGeneralDetails ( $siteRefInput:SiteRefInput! $accountId:ID! ) {
  site ( accountId:$accountId  ) {
    siteGeneralDetails ( site:$siteRefInput  )  {
      site  {
        id 
        name 
      }
      siteType
      description
      siteLocation  {
        countryCode 
        stateCode 
        cityName 
        timezone 
        address 
      }
      preferredPopLocationSiteGeneralDetailsPayload: preferredPopLocation  {
        primary  {
          id
          name
        }

        secondary  {
          id
          name
        }

        preferredOnly
      }
    }

  }  
}