mutation accountManagementUpdateAccount($updateAccountInput: UpdateAccountInput!, $accountId: ID!) {
    accountManagement(accountId: $accountId) {
        updateAccount(input: $updateAccountInput) {
            id
            name
            description
            timeZone
            type
            tenancy
            audit {
                createdBy
                createdTime
            }
        }
    }
}
