query siteStaticHostList ( $accountId:ID! $siteRefInput:SiteRefInput!) {
	site ( accountId:$accountId ) {
		staticHostList ( site:$siteRefInput  )  {
			items {
				hostId
				name
				ip
				macAddress
			}
		}
	}	
}