query networkConfigDhcpSettings ( $accountId:ID!) {
	networkConfig ( accountId:$accountId ) {
		dhcp {
			settings {
				relay {
					enabled
					timeout
					group {
						id
						name
					}
				}
				leaseTime
			}
		}
	}
}