query postureAccountSummaryList ( $accountId:ID! $postureAccountSummaryListInput:PostureAccountSummaryListInput) {
	posture ( accountId:$accountId ) {
		accountSummaryList ( input:$postureAccountSummaryListInput  )  {
			items {
				account {
					id
					name
				}
				score
			}
			paging {
				total
			}
		}
	}	
}