query siteNetworkRange ( $accountId:ID! $networkRangeId:ID!) {
	site ( accountId:$accountId ) {
		networkRange ( networkRangeId:$networkRangeId  )  {
			networkRangeId
			name
			rangeType
			subnet
			translatedSubnet
			localIp
			gateway
			vlan
			azureFloatingIp
			gcpLoadBalancerIp
			primaryManagementIp
			secondaryManagementIp
			dhcpSettings {
				dhcpType
				ipRange
				relayGroupId
				dhcpMicrosegmentation
			}
			mdnsReflector
			internetOnly
		}
	}	
}