query networkConfigDnsSettings ( $accountId:ID!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			settings {
				primaryServer
				secondaryServer
				suffix
				acceptDnsRequestsOnLanInterfaceIp
			}
		}
	}
}