query hardwareManagement ( $accountId:ID! $socketInventoryInput:SocketInventoryInput $socketInventoryDistributionInput:SocketInventoryDistributionInput) {
	hardwareManagement ( accountId:$accountId ) {
		socketInventory ( input:$socketInventoryInput  )  {
			items {
				id
				status
				serialNumber
				socketMac
				socketVersion
				site {
					id
					name
				}
				account {
					id
					name
				}
				shippingDate
				socketType
				orderType
				trackingUrl
				trackingNumber
				shippingCompany
				deliverySiteName
				description
				hardwareVersion
				isPrimary
				registrationStatus
				availableUpgradeVersions
				upgradeStatus
				upgradesPaused
			}
			pageInfo {
				total
			}
		}
		socketInventoryDistribution ( input:$socketInventoryDistributionInput  )  {
			items {
				socketType
				hardwareVersion
				count
			}
		}
	}	
}