query networkConfigDnsSuffixSetList ( $accountId:ID! $networkConfigDnsSuffixSetListInput:NetworkConfigDnsSuffixSetListInput!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			suffixSetList ( input:$networkConfigDnsSuffixSetListInput   ) {
				items {
					id
					name
					suffix
					audit {
						updatedTime
						updatedBy {
							id
							name
						}
					}
				}
				paging {
					total
				}
			}
		}
	}	
}