query networkConfigDhcpRelayGroup ( $accountId:ID! $networkConfigDhcpRelayGroupRefInput:NetworkConfigDhcpRelayGroupRefInput!) {
	networkConfig ( accountId:$accountId ) {
		dhcp {
			relayGroup ( input:$networkConfigDhcpRelayGroupRefInput   ) {
				id
				name
				server
			}
		}
	}
}