query postureFindingList ($accountId: ID!, $postureFindingListInput: PostureFindingListInput!) {
	posture(accountId: $accountId) {
		findingList(input: $postureFindingListInput) {
			items {
				id
				externalId
				checkId
				name
				appInstance
				description
				impact
				impactedEntities {
					id
					type
					name
				}
				additionalInfo {
					key
					value
				}
				muteStatus
				muteReason
				mutedAt
				muteDurationInDays
				resolutionStatus
				checkDefinition {
					id
					name
					description
					tags
					impact
					recommendedActions {
						recommendedAction
						recommendedActionLink {
							text
							url
						}
					}
					suppressedStatus
					category {
						id
						name
					}
					domain {
						id
						name
					}
					area {
						id
						name
					}
					complianceFrameworks
					complianceControls {
						framework
						key
						title
						description
					}
					application
					checkType
					securityDomain
				}
			}
			paging {
				total
			}
		}
	}
}
