query policyReadAppTenantRestricitionPolicy($accountID: ID!) {
  policy(accountId: $accountID) {
    appTenantRestriction {
      policy {
        audit {
          publishedBy
          publishedTime
        }
        enabled
        revision {
          changes
          createdTime
          description
          id
          name
          updatedTime
        }
        rules {
          audit {
            updatedBy
            updatedTime
          }
          properties
          rule {
            action
            application {
              id
              name
            }
            description
            enabled
            headers {
              name
              value
            }
            id
            index
            name
            schedule {
              activeOn
              customRecurring {
                days
                from
                to
              }
              customTimeframe {
                from
                to
              }
            }
            section {
              id
              name
              subPolicyId
            }
            severity
            source {
              country {
                id
                name
              }
              floatingSubnet {
                id
                name
              }
              globalIpRange {
                id
                name
              }
              group {
                id
                name
              }
              host {
                id
                name
              }
              ip
              ipRange {
                from
                to
              }
              networkInterface {
                id
                name
              }
              site {
                id
                name
              }
              siteNetworkSubnet {
                id
                name
              }
              subnet
              systemGroup {
                id
                name
              }
              user {
                id
                name
              }
              usersGroup {
                id
                name
              }
            }
          }
        }
        sections {
          access {
            action
          }
          audit {
            updatedBy
            updatedTime
          }
          properties
          section {
            id
            name
            subPolicyId
          }
        }
      }
    }
  }
}

