query networkRange($accountID: ID!, $networkRangeID: ID!) {
  site(accountId: $accountID) {
    networkRange(networkRangeId: $networkRangeID) {
      azureFloatingIp
      dhcpSettings {
        dhcpType
        ipRange
        relayGroupId
        dhcpMicrosegmentation
      }
      gateway
      internetOnly
      localIp
      mdnsReflector
      name
      networkRangeId
      rangeType
      subnet
      translatedSubnet
      vlan
    }
  }
}
