query networkRange ($accountID: ID!, $networkRangeID: ID!) {
	site(accountId: $accountID) {
		networkRange(networkRangeId: $networkRangeID) {
			networkRangeId
			name
			rangeType
			subnet
			translatedSubnet
			localIp
			gateway
			vlan
			azureFloatingIp
			gcpLoadBalancerIp
			primaryManagementIp
			secondaryManagementIp
			dhcpSettings {
				dhcpType
				ipRange
				relayGroupId
				dhcpMicrosegmentation
			}
			mdnsReflector
			internetOnly
		}
	}
}
