query aiSecurity ($accountId: ID!, $aiSecurityAppsInvocationInput: AiSecurityAppsInvocationInput!, $aiSecurityEndUsersSessionConversationInput: AiSecurityEndUsersSessionConversationInput!, $aiSecurityAgentsEventInput: AiSecurityAgentsEventInput!, $aiSecurityAgentsSessionInput: AiSecurityAgentsSessionInput!) {
	aiSecurity(accountId: $accountId) {
		apps {
			invocation(input: $aiSecurityAppsInvocationInput) {
				id
				sessionId
				timestamp
				tokenCount
				guard {
					id
					name
				}
				action
				data {
					message {
						role
						content {
							text
						}
					}
				}
			}
		}
		endUsers {
			sessionConversation(input: $aiSecurityEndUsersSessionConversationInput) {
				userPrompt
				llmResponse
			}
		}
		agents {
			session(input: $aiSecurityAgentsSessionInput) {
				items {
					interactionId
					appActivityType
					time
					content
				}
				paging {
					total
				}
			}
			event(input: $aiSecurityAgentsEventInput) {
				interactionId
				appActivityType
				time
				content
			}
		}
	}
}
