query catalogsCatalogApplicationFqdn ( $accountId:ID! $applicationRefInput:ApplicationRefInput!) {
	catalogs ( accountId:$accountId ) {
		catalogApplication ( input:$applicationRefInput  )  {
			fqdn
		}
	}	
}