query networkConfigDnsForwardingRule ( $accountId:ID! $networkConfigDnsForwardingRuleRefInput:NetworkConfigDnsForwardingRuleRefInput!) {
	networkConfig ( accountId:$accountId ) {
		dns {
			forwardingRule ( input:$networkConfigDnsForwardingRuleRefInput   ) {
				id
				domain
				server
			}
		}
	}	
}